[workspace]
resolver = "2"
members = [
    "crates/deskunion-app",
    "crates/input-capture",
    "crates/input-emulation",
    "crates/input-event",
    "crates/deskunion-ipc",
    "crates/deskunion-cli",
    "crates/deskunion-gtk",
    "crates/deskunion-proto",
    "crates/deskunion-audio",
]
default-members = ["crates/deskunion-app"]

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"
